docker-compose-yaml: docker-compose.yml

project: amazeelabsv4_com

tasks:
  post-rollout:
    #- run:
    # name: config import
    # command: cd web && drush -y cim
    # service: cli
    - run:
        name: db updates
        command: cd web && drush -y updb --cache-clear=0
        service: cli
    - run:
        name: cache rebuild
        command: cd web && drush -y cr
        service: cli

routes:
  insecure: Redirect

environments:
  prod:
    monitoring_urls:
      - "www.amazeelabs.com"
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # this will run the cron once per Hour
        command: drush cron
        service: cli

    routes:
      - varnish:
          - amazeelabs.com
          - www.amazeelabs.com
          - blog.amazeelabs.com
          - events.amazeelabs.com
          - extreme.amazeelabs.com
          - status.amazeelabs.com

lagoon-sync:
  syncers:
    mariadb:
      hostname: "$MARIADB_HOST"
      username: "$MARIADB_USERNAME"
      password: "$MARIADB_PASSWORD"
      port: "$MARIADB_PORT"
      database: "$MARIADB_DATABASE"
      ignore-table:
        - table_to_ignore_in_output
      ignore-table-data:
        - table_to_export_but_whose_data_to_ignore
      local:
        overrides:
          hostname: "$AMAZEEIO_DB_HOST"
          username: "$AMAZEEIO_DB_USERNAME"
          password: "$AMAZEEIO_DB_PASSWORD"
          port: "$AMAZEEIO_DB_PORT"
          database: "drupal"
    drupalconfig:
      emptykey: "emptyvalue"