# Example .lagoon.yml file with lagoon-sync config added which is used by the sync tool.
docker-compose-yaml: docker-compose.yml

project: "lagoon-sync"

#lagoon-api:
#  endpoint: "https://api.main.lagoon-core.test6.amazee.io/graphql"
#  sshKey: "~/$HOME/.ssh/id_rsa"
#  sshHost: "ssh.main.lagoon-core.test6.amazee.io"
#  sshPort: "22"

lagoon-sync:
  ssh:
    host: "example.ssh.lagoon.amazeeio.cloud"
    port: "22"
    privateKey: "~/.ssh/example_id_rsa"
    verbose: true
  mariadb:
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-drupal}"
      password: "${MARIADB_PASSWORD:-drupal}"
      port: "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-drupal}"
      ignore-table:
        - "table_to_ignore"
      ignore-table-data:
        - "cache_data"
        - "cache_menu"
  postgres:
    config:
      hostname: "${POSTGRES_HOST:-postgres}"
      username: "${POSTGRES_USERNAME:-drupal}"
      password: "${POSTGRES_PASSWORD:-drupal}"
      port: "5432"
      database: "${POSTGRES_DATABASE:-drupal}"
      exclude-table:
        - "table_to_ignore"
      exclude-table-data:
        - "cache_data"
        - "cache_menu"
    local:
      config:
        port: "3306"
  mongodb:
    config:
      hostname: "$MONGODB_HOST"
      port: "$MONGODB_SERVICE_PORT"
      database: "MONGODB_DATABASE"
    local:
      config:
        hostname: "$MONGODB_HOST"
        port: "27017"
        database: "local"
  files:
    config:
      sync-directory: "/app/web/sites/default/files"
    local:
      config:
        sync-directory: "/app/web/sites/default/files"
  drupalconfig:
    config:
      syncpath: "./config/sync"
    local:
      overrides:
        config:
          syncpath: "./config/sync"
