

# Below is your configuration for lagoon-sync.
# These data can live in either a separate .lagoon-sync.yml file
# or your .lagoon.yml file.

# If your project is on anything except the amazeeio cluster, which are the defaults
# and you're running lagoon-sync from a local container, you will have to configure
# the SSH and API endpoints. You can grab this information from running the lagoon
# cli's "lagoon config list" which will output the ssh endpoints and ports you need.
# Typically, though, this information is also available in the environment variables
# LAGOON_CONFIG_SSH_HOST and LAGOON_CONFIG_SSH_PORT.
# 
# These, for instance, are the amazeeio defaults
# api: https://api.lagoon.amazeeio.cloud/graphql
# ssh:
#   host: ssh.lagoon.amazeeio.cloud
#   port: "32222"

lagoon-sync:
  mariadb:
    type: mariadb
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-lagoon}"
      password: "${MARIADB_PASSWORD:-lagoon}"
      port:     "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-lagoon}"
  cli:
    type: files
    config:
      sync-directory: "/app/storage/"

