lagoon-sync:
  mariadb:
    config:
      hostname: "$MARIADB_HOST"
      username: "$MARIADB_USERNAME"
      password: "$MARIADB_PASSWORD"
      port: "$MARIADB_PORT"
      database: "$MARIADB_DATABASE"
      ignore-table:
        - "table_to_ignore"
      ignore-table-data:
        - "cache_data"
        - "cache_menu"
    local:
      config:
        hostname: "mariadb"
        username: "drupal"
        password: "drupal"
        port: "3306"
        database: "drupal"
  files:
    config:
      sync-directory: "/app/web/sites/default/files"
    local:
      config:
        sync-directory: "/app/web/sites/default/files"
  drupalconfig:
    config:
      syncpath: "./config/sync"
    local:
      overrides:
        config:
          syncpath: "./config/sync"